# Generated by Django 4.0.6 on 2022-07-27 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('time', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
