# Generated by Django 4.0.6 on 2022-07-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_url_alter_post_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='date',
        ),
    ]
